partykit/partykit

.changeset/flat-walls-mate.md
package-lock.json
packages/partykit/package.json
packages/partykit/src/cli.ts

Here dropped express in favour of node native http server. Express is basically same thing with polluted request and response.
For static serving in the future can be used https://github.com/lukeed/sirv
```diff
du -ckd1 packages/partykit/dist
- 5512
+ 2980
```
Also see that nice red wall in lockfile

Replace express with native http server

---

.changeset/rude-bulldogs-warn.md
packages/partykit/src/cli.ts

I noticed that the optional `preview` param wasn't included in the console log after a deployment.

Add preview to deployed URL output

---

.changeset/healthy-crabs-move.md
packages/partykit/src/cli.ts

For `onRequest`, we were just using the part of the url after `/party` as the room id, which isn't true when we have query params. This quickly fixes that. Thanks @mellson for the catch.

fix: extract room id correctly

---

packages/partykit/src/bin.ts

This PR is a mini-change. I noticed that we weren't able to develop our application using a dev container with `node --enable-source-maps`.
If you try to run `partykit dev` inside a dev container with source maps enabled it will throw ```/usr/bin/env: ‘node --enable-source-maps’: No such file or directory```.
I didn't dig much deeper than that because I could get it working by removing the source maps from the bin file.

Remove source maps from bin

---

packages/y-partykit/package.json

Similar to [this PR](https://github.com/partykit/partykit/pull/69) for partysocket, I need y-partykit working as both esm and cjs.

Make y-partykit compatible with both esm and cjs

---

.changeset/thirty-guests-fetch.md
packages/partykit/src/cli.ts

This required a fix on the platform side, which I've deployed.   It also required a cosmetic fix in the cli, which this patch does.
Fix https://github.com/partykit/partykit/issues/137

Allow deploys by users with capitals in username

---

.changeset/old-experts-jog.md
examples/basic/package.json
examples/basic/partykit.json
package-lock.json
packages/partykit/package.json
packages/partykit/scripts/build.ts
packages/partykit/src/bin.ts
packages/partykit/src/cli.ts
packages/partykit/src/config.ts
packages/partykit/src/tests/config.test.ts
packages/partykit/src/tests/deploy.test.ts
packages/partykit/src/tests/dev.test.ts
packages/partykit/src/tests/public-fixture/index.html

local dev assets + custom builds
- This adds support for serving static assets (in dev only). This makes onboarding a little simpler; starting a new project doesn't require (too much) extra tooling. It's fairly simple, you make a field called `assets` in `partykit.json`, or pass it via cli with `--assets <path>`. In the future we _may_ also deploy these assets to partykit directly, we'll see.
- This also adds support for custom build commands. You may be using some other compile-to-js language, or need to run some codegen, or even compile your client side app; you can now define a command that runs. It looks like this (all fields are optional):
```js
build: {
command: "...", // the command to run
cwd: "...", // the directory to run it "in",
watch: "..." // the directory to "watch" for …
```

local dev assets + custom builds

---

.changeset/quick-guests-camp.md
docs/reference.md
examples/persistence/src/server.ts
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

This adds a couple of APIs based on common usage patterns:
- `room.broadcast(message, without)` lets you broadcast a message to all connections to a room, optionally excluding an array of connection IDs
- the "socket" now includes `.id`
This shouldn't break any code, so I'm comfortable landing it.

feat: refactor PartyKitConnection / PartyKitRoom

---

.changeset/rotten-pillows-hear.md
examples/basic/partykit.json
examples/basic/src/server.ts
examples/basic/src/xyz.ts
packages/partykit/facade/source.ts
packages/partykit/src/cli.ts
packages/partykit/src/config.ts
packages/partykit/src/dev.tsx
packages/partykit/src/server.ts

Not all architectures can be represented with a single 'type' of entity. The interesting ones have multiple types of entities, interconnected by business logic. For example, you could model a chat system with a chatroom entity, a user entity, and a rate limiter entity.
This patch introduces "multiparty" support. You can define multiple modules with the same `PartyKitServer` interface in different modules, and configure them in `partykit.json`, like so:
```js
{
main: "./src/main.ts" // your "main" entity, usually performing supervisory work
parties: {
chatroom: "chatroom.ts",
user: "user.ts",
limiter: "rate-limiter.ts"
}
// ...
}
```
You can then reference these entities via `room.parties.<user/chatroom/limiter>.get('some-id')` and then make an http request to it with `.fetch(req)` or open …

feat: multiparty support

---

.changeset/unlucky-dodos-act.md
packages/partysocket/src/index.ts

This adds an `id` config for `new PartySocket()` that's uses as the value of `_pk`, that becomes the connection id in the backend.
Fixes https://github.com/partykit/partykit/issues/159

fix: configure `_pk` with PartySocket with `options.id`

---

packages/partykit/facade/source.ts
packages/partykit/src/bin.tsx
packages/partykit/src/dev.tsx

The migration to miniflare/workerd seems to have broken `room.env` in development mode. Instead of the `vars` sourced from partykit.json and `--var` flags, `room.env` was being defined as the facade's env (a `DurableObjectNamespace` map).
I've verified this approach works for both the main durable object and any other parties in a multiparty scenario.
I'm not 100% certain that this fix is the best way of achieving the desired outcome, feedback welcome!

Fixes empty `env` in dev mode

---

.changeset/tough-pandas-shout.md
docs/reference.md
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

Developers want access to additional metadata available on every connection. For example, to implement a rate limiter, they need access to the IP address of the client. They may want access to the user agent, some cookie values, or any of the special `cf` properties like geo information, etc. Most of this information is available on the request object when the connection is made, but we don't actually expose that to the developer right now. I propose we do that.
We can expose a third parameter to the `onConnect` method that is the `context` object. For now it'll just be an onject with a single property `request` that is the request object. In the future we can add more properties to this object.
```js
onConnect(connection, room, context) {
const { request } = context;
const { headers } = …
```

feat: add `ctx` to `onConnect`

---

packages/partykit/facade/source.ts
packages/partykit/src/server.ts

_Note: This PR is stacked on top of #157_
Replaces the new `room.getWebSockets` with a `room.connections` property that behaves like the `connections` map we currently use in `onConnect`. Along with moving the Room ID back onto the `room` property in https://github.com/partykit/partykit/pull/157/commits/1f0c4c66e9856bf0c503ecd00b1af06a3ec5e22a, this now makes the Connection and Room APIs identical between `onMessage` and `onConnect`.
Opening PR for early comments. This seems to work correctly in dev mode, but I still need to implement the same behaviour on the platform side.

Replace room.getWebSockets with a shimmed room.connections when using Hibernation API

---

.changeset/giant-clouds-itch.md
.gitignore
packages/partykit/src/bin.tsx
packages/partykit/src/config.ts
packages/partykit/src/dev.tsx

Currently, `.storage` is only held in memory. This is fine for most usecases, but it means if you shutdown the dev process, we lose any state you may have been holding. This PR adds a config/flag `persist` to store this locally. We also turn it on by default. You can pass `--persist false` in the cli, or `persist: false` in config to turn it off (or `true` for default path). You can also pass `--persist some/custom/path` in the cli, or `persist: "some/custom/path" in the config, to use a custom path for the state.
Fixes https://github.com/partykit/partykit/issues/161

feat: persist state locally in dev

---

packages/partysocket/src/tests/reconnecting.test.ts

Closes #173
A good way to verify the flakiness is to use sequence options to shuffle the test order: https://vitest.dev/config/#sequence

Refactor partysocket tests

---

.changeset/quick-knives-exercise.md
packages/partykit/src/server.ts

Fix Response types for `onBeforeRequest` and `onRequest` callbacks.
When you respond from `onBeforeRequest` or `onRequest`, you have to construct a new response using the `new Response()`. 
Unless you've overridden the global `Response` type to refer to `"@cloudflare/workers-types"`, the type is assumed a [Fetch API Response](https://developer.mozilla.org/en-US/docs/Web/API/Response). This is a pain in the ass, especially if you have your PartyKit server code as part of your frontend project.
Because the actual return value will be an instance of whatever Response class is defined in the environment, the type does not matter to us, so let's just allow the user to return either type.
We'll need to do the same for `Request` when landing #178.

Allow user to respond with Fetch API Response

---

.changeset/rude-buses-fix.md
packages/y-partykit/src/index.ts

Currently the type of `conn` for onConnect in y-partykit is WebSocket, which is incompatible with the type definition of onConnect of `partykit/server`.
This PR replaces the type of the connections in `y-partykit` to the correct type.

fix: change type of `conn` to PartykitConenection

---

.changeset/wild-jobs-flow.md
packages/partykit/facade/source.ts
packages/partykit/src/dev.tsx
packages/partykit/src/server.ts

We now allow using `onConnect` with `onMessage`. This lets you get access to the context `{request}`. Warning: You can't use `.addEventListener` when using `onMessage`, but it currently just silently fails. We'll make this an error later.

allow using `onConnect` with `onMessage`

---

.changeset/sharp-dancers-turn.md
packages/partykit/facade/source.ts

Fixes issue where `connections` keeps growing on every connection when opting into Durable Object Hibernation.

Clean up hibernatable connection before invoking event handler

---

.changeset/proud-seas-smile.md
packages/partysocket/src/react.ts
packages/partysocket/src/type-helper.ts

* Add websocket lifecycle event handlers to `usePartyKit` options to reduce need for effects in userland
* Allow `usePartySocket` to provide `startClosed` option to initialize without opening connection
* Fix types for `PartySocket#removeEventListener`
Example:
```tsx
const [messages, setMessages] = useState<string[]>([]);
const socket = usePartySocket({
host: "localhost:1999",
room: "chat-room",
startClosed: true,
onOpen() {
setMessages((messages) => [...messages, "Joined"]);
},
onMessage(event) {
setMessages((messages) => [...messages, event.data]);
},
});
return (
<button onClick={() => socket.reconnect()}>Open</button>
)
```

Improve PartySocket types and React hooks API

---

.changeset/seven-otters-join.md
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

We were using `unstable_initial` to pass info between `onBeforeConnect` and `onConnect`. But it just felt so alien. Now that onConnect also receives request (via https://github.com/partykit/partykit/pull/166), let's just let onBeforeConnect return a Request or a Response. If a Request, it gets passed on to onConnect. Else, it just returns.
This is a breaking change, but it's a minor one, and it's worth it to get rid of `unstable_initial`.

remove `unstable_initial`, and `onBeforeConnect` can now return a `Request`/`Response`

---

.changeset/metal-meals-care.md
packages/y-partykit/src/index.ts

It's better to default to `gc: true` with partykit, so memory is better used in partykit servers. We should also ensure `gc` and `persist` are never used together. So this PR adds a little logic to find a better default, and ensuring the 2 never clash.

y-partykit: better default for `gc`

---

.changeset/giant-apricots-reply.md
packages/partykit/facade/source.ts

Let's not create the `parties` object on every request/connection, and instead cache it after first creating it.

cache `parties` object arter creating it

---

.changeset/warm-bears-behave.md
packages/partykit/facade/source.ts

When using hibernation, we should cache initialised connections, or else we end up doing it for every message, which seems wasteful.

cache hydrated connections

---

.changeset/cuddly-foxes-rush.md
packages/partysocket/src/index.ts

Allows `partysocket` to connect to a party other than the main party, e.g. 
```js
const socket = usePartySocket({
host: "localhost:1999",
party: "chatroom",
room: roomId,
});
```

Connect to subparty

---

.changeset/few-houses-notice.md
packages/partysocket/src/tests/reconnecting.test.ts
packages/partysocket/src/ws.ts

The implementation of `ReconnectingWebSocket` tests whether a WebSocket class is valid by the presence of a static field that's not available on CF's/PK's WebSocket class. It's a bit much anyway, so we just remove the test.

fix: make PartySocket work inside cloudflare/partykit

---

.changeset/tough-dots-hunt.md
packages/partykit/src/dev.tsx
packages/partykit/src/tests/dev.test.tsx

The server we spin up makes our tests flaky. we don't have tests for dev logs anyway right now, so let's disable them.

disable inspector for tests

---

.changeset/tall-gorillas-learn.md
packages/partykit/facade/source.ts
packages/partykit/src/tests/dev.test.tsx

fix: don't forward request to room without an `onRequest` handler

---

.changeset/shy-parrots-repair.md
packages/y-partykit/src/provider.ts

This adds a `party` parameter to the options bag for `YPartyKitProvider`

configure `party` in `y-partykit`

---

.changeset/seven-turkeys-tickle.md
packages/partykit/src/dev.tsx

This a remnant from our previous arch, we don't need this anymore. (and it's getting overwritten anyway, so it's not functional)

don't minify code in dev

---

.changeset/hip-cobras-tan.md
packages/partykit/src/config.ts
packages/partykit/src/countdown.tsx

When we're logging in, we open up a browser for a user to paste a code into github. We currently open it immediately, so users aren't sure what's happening. This PR adds a delay for a few seconds, with clearer instructions on what's happening.

delay login browser popup for 5 seconds

---

.changeset/mean-ads-rush.md
packages/partysocket/src/index.ts

if we don't check if crypto is defined or not.
it gives the following error.
```
ReferenceError: crypto is not defined
```

check if crypto is defined

---

.changeset/fuzzy-geese-yawn.md
packages/y-partykit/src/storage.ts

So, out persistence layer has a 128kb limit on values, but `y-partykit` should/could be used for documents bigger than that. So we implemented a chunking strategy that break up values across multiple keys. When making keys for these, we didn't pad the generated indexes, which meant that for sufficiently large values, we might have assembled them back in the wrong order (because lexicographical sorting). This is a fix for that. It's a breaking change, but oddly I haven't heard from people who've faced the problem at all.

fix: properly sort chunking in y-partykit for big values

---

.changeset/green-schools-deny.md
packages/partysocket/src/ws.ts

Log an error if `EventTarget` isn't available when using `partysocket`, with instructions on fixing it.

partysocket: warn if EventTarget is not available

---

.changeset/breezy-carrots-dance.md
examples/basic/src/client.ts
examples/blocknote/package.json
examples/blocknote/src/client.tsx
examples/lexical/package.json
examples/lexical/src/client.tsx
examples/monaco/src/client.tsx
examples/persistence/src/client.ts
examples/wasm/src/client.ts
examples/yjs/src/client.ts
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx

We can actually make a pretty good guess to what the host is for both dev and deploy, so let's define it when compiling, and remove a bunch of boilerplate in the process.

feat: define a default `process.env.PARTYKIT_HOST`

---

packages/partykit/src/bin.tsx
packages/partykit/src/cli.tsx
packages/partykit/src/commands/login.tsx
packages/partykit/src/config.ts
packages/partykit/src/featureFlags.ts

Branching this out of #221 to make it easier to review.
- Implements a very simple feature flagging system.
- Caches previously used flags on disk
- Refreshes flags lazily on every use to avoid blocking, so new flags will only be applied on next use
- Falls back to default flags
- Chooses login mechanism based on feature flag
- Defaults to `github` for now, we'll change it to `clerk` on launch day
- On launch day + `n`, we can remove `github` from supported platforms, which will force all existing clients to migrate
- Adds a `--provider` argument to `partykit login` for early testing (to be removed once stable)

Migrate to Clerk authentication behind a feature flag

---

.changeset/fifty-cats-deliver.md
packages/create-partykit/src/index.tsx

- ensure instructions are logged on new project
- don't log long git commit info
- output path where project was made

tweaks to create-partykit

---

.changeset/hot-rice-fail.md
packages/partykit/src/server.ts

The types on `onBeforeRequest`/`onBeforeConnect` were causing errors, this should fix 'em

fix: type signatures on `onBeforeRequest`/`onBeforeConnect`

---

.changeset/breezy-bananas-clean.md
packages/partykit/src/dev.tsx

We had a bug where newly created assets weren't being served on dev, this should fix that.

fix: serve newer assets on changes

---

.changeset/mean-buckets-hear.md
packages/create-partykit/README.md
packages/create-partykit/src/index.tsx

we were trying got be clever and not make a package.json if there was a parent (that's wasn't a monorepo root). Turns out folks have package.json's all the time. So this just always makes a package.json, and only runs the installer in the root package,json dir f it's a monorepo/has workspaces

create: always make a package.json

---

.changeset/thin-scissors-guess.md
package-lock.json
packages/create-partykit/js-template/tsconfig.json
packages/create-partykit/package.json
packages/create-partykit/src/index.tsx
packages/create-partykit/ts-template/tsconfig.json
packages/partykit/package.json
packages/partykit/src/cli.tsx
packages/partykit/src/config.ts
tsconfig.base.json

When we create a project, we shouldn't try to create a git repo if we're initialising inside another git repo (like a monorepo). This PR detects whether there's a git folder and skips the git repo creation part.
Additionally:
- we switch away from `find-config` to `find-up` everywhere, since it works on both files and directories
- I also took the opportunity to enable `verbatimModuleSyntax` in our tsconfig, which makes vscode import types correctly when we auto-import

create: don't initialise git repo inside another

---

.changeset/five-items-promise.md
packages/partykit/src/dev.tsx
packages/partykit/src/tests/dev.test.tsx

We weren't looking for free ports when starting up partykit dev. We run a few servers; the runtime, the assets server, and an inspector port. This PR uses preferred ports when starting up, and finds free ports when not.

run multiple instances simultaneously

---

.changeset/clean-ladybugs-kick.md
packages/partykit/src/dev.tsx

We were adding a bunch of listeners on the miniflare server that we weren't cleaning up, and the dependency array was wrong. This PR fixes those up, while also conveniently fixing the issue where console.log wasn't working after the first compile failure.

unload listeners on mf server / fix live reload console logging

---

.changeset/rare-eagles-share.md
package-lock.json
packages/partykit/.env.development
packages/partykit/.env.production
packages/partykit/package.json
packages/partykit/scripts/build.ts
packages/partykit/src/auth/clerk.ts
vitest.setup.js

We need to connect to the dev clerk instance when doing local development against locally running dashboard.
- `npm start` -- runs against local `partyworker`, `partycentral` and development Clerk instance
- `npm run dev:remote` -- runs against production instances (useful for dev/debugging without setting up local dev for everything else).
Uses `dotenv` instead of `cross-env` to reduce config duplication in package.json.

Separate modes for local dev against local dev vs production

---

.changeset/tasty-cups-jog.md
packages/y-partykit/src/provider.ts

- Fix unnecessary `Y.js` import
- Polyfill missing `WebSocket.[STATUS]` codes
- This change could also have been made by checking for `WebSocketStatus` explicitly, but because the JS standard WebSocket type definition claims they exist, I'm 100% sure this will bite other people as well
-  Disable Broadcast Channel by default

Make YProvider work in workers runtime

---

.changeset/fuzzy-oranges-shake.md
packages/partykit/src/dev.tsx

In `dev` we have some issues with the way we initialise/restart servers
- if an external process is generating assets, and it does it quickly, then we end up crashing the assets server
- we were restarting the assets folder watcher whenever the assets watcher restarted
- we weren't cleaning up the assets folder watcher on effect rerun
- we weren't cleaning up the custom build folder watcher on effect rerun
So, the fixes:
- debounce setting the assets map (100ms, is short enough to not be noticeable, but long enough to let esbuild manager a restart)
- close the assets build watcher correctly
- don't restart the assets build watcher incessantly
- close the custom build watcher correctly

fix: timing issues with assets/build server

---

.changeset/giant-feet-bathe.md
packages/partykit/src/dev.tsx
packages/partykit/src/inspect.ts

Ok I figured it out. We were adding listeners to the inspector websocket server. I also found some stray listeners we weren't cleaning up. I also removed the debouncing setup for the assets server. This is looking a lot better now.

fix: actually fix the listeners/crash scenario

---

.changeset/purple-rivers-learn.md
packages/partykit/src/dev.tsx

Stealing this idea from wrangler: this adds a floating bar with hotkeys to open a browser, clear the console, or simply exit the process. We'll add an inspector button later!

feat: add hot keys to open a browser, clear console, exit

---

.changeset/angry-olives-fold.md
packages/partykit/src/auth/clerk.ts
packages/partykit/src/auth/device.ts
packages/partykit/src/bin.tsx
packages/partykit/src/cli.tsx
packages/partykit/src/config.ts

Adds a new `npx partykit token generate` command that allows you to generate a new Clerk client session.
From code perspective, this is ready to land, but since it relies on the yet-unpublicised dashboard, it may make sense to only ship this when we're ready to onboard users there.
While developing this, I made a few other improvements to the session management worflow:
- Sessions are now tagged with custom user agents, so the user can differentiate between CLI sessions and (CI) token sessions in the Clerk account management page
- Sessions are expired upon logout (because our device session length is very long, these will otherwise pile up)

Generate session tokens for CI

---

.changeset/happy-needles-call.md
packages/partykit/src/dev.tsx

fairly common behaviour with other CLIs, just adding it to ours as well.

add new lines when hitting return in `dev`

---

.changeset/funny-islands-help.md
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx
packages/partykit/src/nodejs-compat.ts

We support some node builtins, so we shouldn't try to compile them into the bundle.

don't compile node builtins that the platform supports

---

.changeset/long-ways-swim.md
README.md
packages/y-partykit/README.md
packages/y-partykit/package.json
packages/y-partykit/src/provider.ts
packages/y-partykit/src/react.ts

This adds a react hook version of the YPartyKitProvider.
```tsx
import useYProvider from "y-partykit/react";
function App() {
const provider = useYProvider({
host: "localhost:1999",
room: "my-document-name",
doc: yDoc, // optional!
options,
});
}
```

y-partykit/react: a hook version of the provider

---

.changeset/lovely-tigers-marry.md
apps/blog/src/content/blog/partyserver-class-api.md
apps/docs/src/content/docs/guides/authentication.md
apps/docs/src/content/docs/guides/index.md
apps/docs/src/content/docs/guides/responding-to-http-requests.md
apps/docs/src/content/docs/guides/serving-static-assets.md
apps/docs/src/content/docs/guides/using-multiple-parties-per-project.md
apps/docs/src/content/docs/how-partykit-works.md
examples/class/src/server.ts
packages/create-partykit/js-template/src/server.js
packages/create-partykit/ts-template/src/server.ts
packages/partykit/init/index.js
packages/partykit/init/index.ts
packages/partykit/src/server.ts

This changes the naming of our exported types from `partykit/server`. The motivation here was aesthetic/simplification. Most of the exports los the `Party` prefix; i.e. `PartyServer` becomes `Server`, `PartyConnection` becomes `Connection`, and so on. If you look at the class example, this doesn't drastically change the code; the import becomes a lot shorter (`import type * as Party from 'partykit/server'` gets all the required types) and required types are taken by `Party.*`.
I also did a run on all the docs/templates and the blog post, but lemme know if I missed anything!

change naming of /server exports

---

.changeset/modern-steaks-drop.md
packages/partykit/src/cli.tsx
packages/partysocket/src/react.ts

This fix should pick up the latest versions of partykit /partysocket when installing. We were using the previous beta logic when every package was on the same version. This patch picks up the latest versions of both and uses it.
(also sneaking in a quick types fix for usePartySocket)

fix: `init` doesn't install the right versions of packages

---

.changeset/ninety-poems-film.md
packages/y-partykit/src/provider.ts

It's common for `host` and `room` parameters to be accidentally undefined e.g. when an environment variable is not set.
This PR adds better error messages
```
TypeError: Cannot read properties of undefined (reading 'replace')
```

Improve YPartyKitProvider errors

---

.changeset/tasty-drinks-provide.md
package-lock.json
packages/create-partykit/package.json
packages/partykit/package.json

This is an attempt to fix an issue with `create-partykit` command process exiting unexpectedly.
I've verified that pinning `ink@4.3.1` will fix this issue in isolation, but due to the monorepo build this may not fix the issue in the deployed version. Only way to find out is to land this, deploy to beta channel and test.

Fix `create-partykit` crash

---

apps/site/package.json
apps/site/src/components/HeroLoop.jsx
package-lock.json

Now that the website is in the monorepo, we were getting dependency conflicts for different versions of `react` defined by `peerDependencies` in [react-text-loop](https://www.npmjs.com/package/react-text-loop).
This replaces the antiquated package with the modernized [react-text-loop-next-18](https://www.npmjs.com/package/react-text-loop-next-18) fork.
The fork isn't actively maintained either. Eventually, we want to get rid of the package entirely, but I couldn't find anything else that does the same thing, and we'll be redesigning the website soon enough.

Migrate react-text-loop -> react-text-loop-next-18

---

.changeset/short-eagles-yawn.md
examples/basic/src/server.ts
package-lock.json
packages/create-partykit/package.json
packages/create-partykit/rdt-mock.js
packages/create-partykit/scripts/build.ts
packages/partykit/package.json
packages/partykit/rdt-mock.js
packages/partykit/scripts/build.ts
packages/partykit/src/tests/dev.test.tsx
packages/partykit/src/tests/ink-testing-library.ts

This brings back packaging of dependencies for partykit (and introduces it for create-partykit). We had previously disabled it for deps because of esm/cjs nonsense, but we've now figured out how to make them play decently together.
I had to fork ink-testing-library because of https://github.com/vadimdemedes/ink-testing-library/pull/23, I'll remove it once that PR is merged.
This also updates ink to 4.4.1, which fixes our previous issue where it was exiting early.

partykit: bundle dependencies

---

.github/workflows/prerelease.yml
.github/workflows/pullrequest.yml
.github/workflows/release.yml
package.json

This patch replaces the caching and npm ci steps with a plain bun install in CI for all workflows. It appears to consistently shave off about a minute, pretty good.

Use bun install in CI

---

.changeset/tasty-experts-rule.md
packages/partykit/src/auth/clerk.ts

This was broken by #339 -- the Clerk import is now correctly understood as a default import, so the previous workaround is no longer necessary.

Fix Clerk login

---

apps/docs/src/content/docs/guides/serving-static-assets.md

As I was working on my PartyKit app, I tried setting the `serveSinglePageApp` setting as it was demonstrated in the docs.
As it turns out, this isn't how the config is implemented in the code though. Setting it to `singlePageApp` worked correctly.
This PR changes the docs to match the correct behavior.

Change serveSinglePageApp to singlePageApp in docs

---

.changeset/strange-carrots-scream.md
packages/create-partykit/src/index.tsx

Fixes #341 and closes #309. Also expands the legal paths to any relative path from the current working directory.
Valid paths:
```
.
./
../
./hello
../hello
../../hello
hello
hello/world
```
Invalid paths
```
hello world
./hello world
hello.json
/hello
```
As per last invalid path example, we still don't allow absolute paths. We could enable this as well, but it would have required changing the path resolution code elsewhere, and writing to absolute paths is most likely unintended, so I didn't enable it for now.

Fix `./` paths and other relative paths for create-partykit

---

.changeset/few-carrots-care.md
packages/partykit/facade/connection.ts
packages/y-partykit/src/provider.ts

Discovered a discrepancy between hibernating and non-hibernating socket behaviour: in hibernation mode, the `getConnections()` method returned sockets that were closing or recently closed.
This is in fact [documented behaviour](https://developers.cloudflare.com/durable-objects/api/hibernatable-websockets-api/#state-methods-for-websockets):
> getWebSockets() may still return websockets even after ws.close() has been called. For example, if your server-side WebSocket (the Durable Object) sends a close, but does not receive one back (and has not detected a disconnect from the client), then the connection is in the CLOSING “readyState”. The client might send more messages, so the WebSocket is technically not disconnected.
However, for our use case, we want the behaviour to match the manual …

Only yield open hibernating connections from getConnections()

---

apps/docs/src/content/docs/reference/y-partykit-api.md

The PR documents the `useYProvider` hook - the contents are taken from the package readme

documents useYProvider hook

---

.changeset/neat-ghosts-cry.md
packages/create-partykit/js-template/src/client.js
packages/create-partykit/ts-template/src/client.ts

When server hot-reloads (for example), the clients reconnect and another ping sequence starts. You then get multiple pings from each browser. This change cancels an existing sequence if it exists.

Reduce double ping in client.js/ts

---

apps/site/src/components/Header.astro
apps/site/src/components/Hero.astro

There's a bug on mobile where the header can't compress horizontally, and this adds a right-hand margin for the rest of the site. Existing:
This PR allows the header to shrink down just enough to avoid this happening:
It also removes a rogue right-hand black border on the hero iframe.

Compress the header horizontally on small screens

---

.changeset/witty-eagles-wonder.md
packages/partykit/facade/source.ts
packages/partykit/src/dev.tsx
packages/partykit/src/server.ts

This exposes the parent level name of the party (default "main", other wise the key from `parties` in `partykit.json`

add `party.name`

---

.changeset/little-brooms-stare.md
packages/partysocket/src/ws.ts

looks like tools like stackblitz defines `process` on the fronted (???), but when we test for process.versions.node it crashes. This fixes the detection logic.
(PartyKit doesn't work in stackblitz yet, but atleast this error shouldn't happen)

partysocket fix: don't crash in stackblitz

---

.changeset/clever-badgers-sing.md
packages/partysocket/src/index.ts

This exposes the top level party 'name' on partysocket. Since urls for partysocket are 'static' we can also override the base implementation and expose the calculated url as well.

expose `partySocket.name`, and a static `.url`

---

.changeset/tasty-toys-applaud.md
packages/partykit/src/cli.tsx

Seems like the static asset deployment wasn't correctly sending the `preview` parameter.

Fix static asset deployment

---

.changeset/young-terms-shop.md
packages/partykit/package.json
packages/partykit/scripts/build.ts

clipboardy comes with fallback binaries to use (esp. in windows). If we bundle it into the partykit bundle, then the references to those binaries fail. So we mark it as an external so it installs separately and resolves the binaries correctly.

mark `clipboardy` as an external dependency

---

.changeset/quiet-mice-chew.md
packages/partykit/schema.json
packages/partykit/src/cli.tsx
packages/partykit/src/config-schema.ts

While fixing #387,  I noticed that deleting preview deployments fails because the `preview` field is not allowed on `Config`.
This makes sense, because the `preview` field is a documented option on partykit json, but it can be provided as a config override with a `--preview` flag. 
I could have fixed this by removing the `preview` flag before we validate the config, but I think it would be useful to be able to set the `preview` flag in partykit.json, so I added it to the valid config schema instead.

Fix deleting preview deployments

---

.changeset/witty-flies-flash.md
packages/partykit/src/auth/clerk.ts
packages/partykit/src/commands/login.tsx
packages/partykit/src/config.ts
packages/partykit/src/featureFlags.ts

This PR does the following:
- Makes `partykit login` use the PartyKit (Clerk) provider by default
- Changes `partykit login` behaviour so that if you have an old GitHub token, it will login again using the PartyKit provider
- Fixes a bug in feature flags implementation that prevented new flags being loaded
The feature flags in this case are not necessary as we are also changing the default config on the CLI side, but it'll be useful to switch back to GitHub in case we have any hiccups with the dashboard/clerk during the rollout.

Change default login method to partykit

---

.changeset/three-pants-search.md
package-lock.json
packages/create-partykit/package.json
packages/create-partykit/src/index.tsx
packages/partykit/package.json
packages/partykit/src/cli.tsx

some references to `fetch` weren't being imported from undici. global fetch was introduced only in node 18. so the partykit cli (specifically `init`) and create-partykit weren't working on node 16. This fixes that issue (tho we should phase out node 16 support soon)

fix: work on node 16 again

---

.changeset/red-parents-suffer.md
package-lock.json
packages/partykit/package.json
packages/partykit/src/cli.tsx

Currently when you run `npx partykit@latest init` in an existing project and choose to add partykit to existing `package.json`, we add dependencies to the JSON content and write it back to `package.json` file with 2 spaces here: https://github.com/partykit/partykit/blob/a01be0da91b0b8b18cc50a63bb2a655b08178455/packages/partykit/src/cli.tsx#L217
This is a problem when the existing `package.json` uses a different indentation like 4 spaces / tabs since it's a bit confusing to see a huge `git diff` after the command. Ran into this when running `npx partykit@latest init` in a SvelteKit project since it uses tabs for formatting by default. While one can run re-format the file to see the actual diff, I think it'll be a good experience to keep the existing indentation. And @sindresorhus has a …

Use existing indentation of package.json during partykit init

---

.changeset/cool-peaches-argue.md
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx

Fixes #328 
In Windows devices, the assetsMap was generating file paths with double backslashes, resulting in incorrect file paths. This PR addresses this issue by replacing the double backslashes with single forward slashes, ensuring that the file paths are correct and functional.

[fix] filePath in windows

---

apps/docs/src/content/docs/guides/setting-up-ci-cd-with-github-actions.md

Updated the CI guide based on my experience settings this up. It looks like you can't create a repository secret with name starting with `GITHUB_` (error message below for reference) 
Also tweaked it to link to the page where you can create PAT, which is what I did.
Sample workflow which works for me - https://github.com/tsriram/svelte-party-demo/blob/321a8445bbf7322e8ec63962690922729fe1f510/.github/workflows/deploy-partykit.yml
Sample Action run for reference - https://github.com/tsriram/svelte-party-demo/actions/runs/6276609049
PS: Feel free to nitpick on the copy / edit it directly :)

Update CI guide

---

apps/docs/src/content/docs/reference/partysocket-api.md

lol I thought there was a bug in the partySocket lib when I was seeing the log `connected` even when the servers were not running, turns out it was a typo in the docs from where I copy/pasted the code. Fixed that

fixed typo in docs for PartySocket (Client Api)

---

apps/docs/src/content/docs/reference/partysocket-api.md

Presumably this is what comes from partykit.json. If dots are possible, it at least makes the docs slightly more confusing, because it's ambiguous if the host is something like `party.my-project.party.dev`

Make it more clear in docs how host name is built

---

.changeset/kind-brooms-flash.md
apps/docs/src/content/docs/reference/partykit-configuration.md
packages/create-partykit/js-template/partykit.json
packages/create-partykit/src/index.tsx
packages/create-partykit/ts-template/partykit.json
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx
packages/partykit/src/tests/deploy.test.ts

We should be adding a default compatibility date to new projects. Further, for projects that don't have one, we should warn that they should, and default to the latest compatibility date that we can. This PR adds that behaviour for both create, dev and deploy

add a default compatibility date

---

.changeset/famous-peas-smoke.md
packages/partykit/src/bin.tsx
packages/partykit/src/dev.tsx

When we have errors in the code, we log the error, but it uses line numbers from the output worker, which aren't helpful. Particularly because we don't output the actual worker to disk anyway, so they can't figure out where the error is coming from. It's really bad for large codebases.
Figuring out debugging is a top level concern for us; we want to have sourcemaps, breakpoints, devtools - the works. But until we get there, we should help people find where errors are coming from.
This adds an experimental `--unstable_outdir <path>` to `partykit dev` that spits out the actual code that we run in the dev environment, so folks can inspect it. The output code also inlines filenames, so that should help as well. This should hold folks until we have a better debugging story.

experimental: `dev --unstable_outdir <path>`

---

.changeset/ten-olives-joke.md
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx

- Uses UTC dates for dev mode timezone and the dev/deploy warnings
- Allows deployment platform to decide default date when one is not provided (do not send default date on deploy)

Fix compatibility date timezone

---

.changeset/unlucky-squids-wink.md
packages/y-partykit/src/index.ts
packages/y-partykit/src/provider.ts

We had a ping-pong loop with partykit to keep the object alive, but it's not necessary. This patch removes it.

y-partykit: remove ping-pong

---

.changeset/rare-insects-poke.md
packages/partykit/facade/connection.ts
packages/partykit/src/server.ts

Fixes #434 
Fixes root cause for performance issue https://github.com/partykit/sketch-voronoi/pull/4
1. In hibernation mode, PartyKit stores basic connection information such as connection id and url in the websocket attachments, so that we can regain access to them when the object wakes up from hibernation.
2. Any user invocation of`serializeAttachment` overwrote the fields internally managed by PartyKit
3. When the object next wakes up in reaction to a message, we assert that the information we store is still present. This assertion fails, and causes a silent error.
We "namespace' partykit fields and user fields, and patch the `serializeAttachment` and `deserializeAttachment` fields to return only the value from the user namespace. Internally, we use the getters for the private fields, …

Ensure that user attachments don't clobber system attachments used by PartyKit

---

examples/class/src/server.ts
packages/partykit/facade/connection.ts
packages/partykit/facade/source.ts
packages/partykit/src/server.ts
packages/y-partykit/src/provider.ts

I'm proposing the following API to replace the current serialize/deserializeAttachment API:
```ts
type State = { foo: string, baz?: number } ;
onConnect(conn: Party.Connection<State>) {
// set state
conn.setState({ foo: "bar"  });
// read state
console.log(conn.state); // { foo: "bar" }
// update state
const updatedState = conn.setState(prevState => ({ ...prevState, baz: 1 });;
console.log(updatedState) // { foo: "bar", baz: 1 };
}
```
A more complete example of what this change would look like in user code: https://github.com/partykit/sketch-voronoi/pull/5/files
The same API works for hibernating and non-hibernating connections, and provides optional type safety by adding a generic parameter on `Connection`.
In the last week, we've ran into a number of issues with the WebSocket …

Add new `connection.state` / `connection.setState` API

---

apps/docs/src/content/docs/guides/responding-to-http-requests.md

Link to examples from `Responding to HTTP requests` guide page looks to be broken. Fixing it.

Fix broken link in docs

---

.changeset/four-actors-draw.md
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

WebSocket messages can be `string | ArrayBuffer | ArrayBufferView`, this patch fixes the types to allow that. The implementation remains the same (and otherwise always worked).

fix: .send and .broadcast can send ArrayBuffers

---

apps/docs/src/content/docs/guides/authentication.md
apps/docs/src/content/docs/reference/partysocket-api.md
packages/partykit/src/server.ts
packages/partysocket/src/index.ts

This enables people to pass dynamic parameters such as authentication tokens upon reconnect.
As a side effect, we can no longer provide a static party `url`, so this is now available as `roomUrl`. `url` now reverts to the original base class behaviour, where it returns the dynamic url of the websocket (or an empty string if websocket is not yet initialized).
This is a breaking change, but AFAIK our only user of this behaviour is @jamesgpearce.

Allow passing PartySocket.query as a function

---

.changeset/empty-kiwis-brush.md
apps/docs/src/content/docs/reference/y-partykit-api.md
examples/yjs/src/client.ts
packages/y-partykit/src/provider.ts

Useful for e.g. passing authentication token and refreshing them on reconnect.

Allow passing a function to YPartyKitProvider options.params

---

.changeset/violet-days-retire.md
packages/partykit/src/nodejs-compat.ts

crypto was missing from the node_compat, and users can't use the node:crypto.
I've added it, & it works. well it works on my device 😂

added missing crypto from node_compat

---

.changeset/rude-bikes-agree.md
packages/partykit/src/auth/device.ts

It seems Chrome is rolling out the new Private Network Access initiative that improves the security of making public websites (e.g. dashboard.partykit.io) to connect to private address spaces (e.g. the authentication callback server we spin up at localhost).
It's not 100% clear to me which way this initiative is going, but as per the [preflight specification](https://developer.chrome.com/blog/private-network-access-preflight/), we now respond with the correct headers to allow this variant of it.
According to the above blog post, this may not be sufficient in the long term, as they seem to be moving towards blocking public-private HTTP traffic entirely. Mitigations for that are described in https://developer.chrome.com/blog/private-network-access-update
This PR fixes known issue #471, and …

Allow preflight requests when Chrome Private Network Access is enabled

---

.changeset/tricky-teachers-occur.md
packages/partykit/src/auth/device.ts

Fixes remaining issue on #471 for Safari/Brave.
WebKit chooses not to observe the W3C Mixed Content specification and blocking localhost requests from public `https` websites despite the spec explicitly allowing it. See: https://bugs.webkit.org/show_bug.cgi?id=171934
This PR adds a workaround to perform authentication as a navigation event if the initial callback fails.
This is how `wrangler` does it, as well.

Fix login on WebKit

---

.changeset/smart-adults-swim.md
packages/partysocket/src/index.ts
packages/y-partykit/src/provider.ts

Minor API tweaks on top of the changes we landed on Friday.

Allow and ignore null query variables in partysocket and y-partykit/provider

---

.changeset/few-owls-wait.md
packages/partysocket/package.json

This dependency causes way too many issues, especially since react doesn't work with multiple versions. Let's see if removing it helps.

don't mark react as a dependency for partysocket

---

apps/docs/src/content/docs/reference/y-partykit-api.md
packages/y-partykit/src/index.ts
packages/y-partykit/src/storage.ts

Adds options to control how to persist the document to PartyKit room storage.
The goal here is to not break existing clients, and provide a migration path to more sensible strategies.
- `{mode: "snapshot"}` — persist full document snapshot (recommended)
- `{mode: "history", maxUpdates, maxBytes }` — persist document edit history
- `true` — Equivalent to `{ mode: "history" }` (deprecated, use `{ mode: "history "}` instead)
- `false` — Do not persist document or history (default value)
See diff for better options.

[PROPOSAL] y-partykit storage modes

---

.changeset/twelve-snails-suffer.md
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

This lets you pass a "sub" path to a sub party `.fetch()` or `.socket()` (and adds being able to pass a RequestInit to `.socket()`). This make it possible to do routing more cleanly inside sub parties, making them more versatile.
--- 
This does NOT expose the "sub" path inside the party. It might make this more useful, but it's not clear where to expose it yet.
This does NOT accept URLs or Requests as the first parameter yet. 
I also want to do some more testing on this, but opening it up for a review.

pass sub path/init during subparty .fetch()/.socket()

---

.changeset/tidy-olives-pretend.md
packages/partysocket/package.json

tsup ignores pnly dependencies marked in package.json under dependencies/devDependencies. Since we don't have react in here, it was bundling it into partysocket/react, leading to multiple versions being loaded into the same space. This explicity excludes react from the bundle.

partysocket: don't bundle react into the built assets

---

.changeset/three-hairs-vanish.md
examples/yjs/src/client.ts
packages/y-partykit/src/chunking.ts
packages/y-partykit/src/index.ts
packages/y-partykit/src/provider.ts

The Workers platform rejects WebSocket messages when they are above 1MB.
The Y.js provider does not like this, and end up in a nasty reconnect/retry loop, which will spam the room with very large messages.
Chunk large Y.js update messages to 1MB chunks and reassemble them on the server side.
This implementation is not 100% resilient to network issues such as dropped messages, but I've tried to validate the inputs as well as I can and not pass malformed messages to the handler on the server. In this case, the worst case behaviour is the same as it was before applying this fix in the first place.
Generally, limiting WebSocket message sizes is a good idea, but with Y.js it's reasonable for the document size to grow to exceed 1MB.  Sending the large message should only happen on initial sync, …

Support Y.js messages > 1MB

---

apps/blog/src/pages/404.astro

I've been really not enjoying the 404 page on the blog because the shrug feels like we don't care.
before we design one 404 page across all sites, I just deleted the shrug.

deletes 404 shrug

---

.changeset/heavy-mails-raise.md
packages/partysocket/src/index.ts

This patch lets you add `path: string` to `new PartySocket({...})` and point to a subpath in a room. This is a client side analog to the recent subpath support we added to multiparty `.fetch()`/`.socket()`

partysocket: add subpath support

---

.changeset/nine-jobs-mate.md
packages/partykit/facade/fetch-static-asset.ts
packages/partykit/facade/source.ts

We had a bug when picking out the room name from `/party/:id/*`, it would pick the whole subpath instead. This fixes it.

fix: get proper room id from `/party/:id/*`

---

.changeset/young-wolves-cry.md
packages/partykit/src/config.ts
packages/partykit/src/fetchResult.ts

Fixes #501. Because Clerk session tokens are only valid for 1 minute (and this can not be extended), instead we refresh the token on every request (with a 30 second cache, so shorter operations will never have to refresh).

Fix session expiration for long-running deployments

---

apps/docs/.astro/types.d.ts
apps/docs/astro.config.mjs
apps/docs/src/content/docs/add-to-existing-project.md
apps/docs/src/content/docs/index.mdx
apps/docs/src/content/docs/quickstart.md

This PR:
- refreshes the content on "What is PartyKit"
- fixes an error in the content around running dev server (the experience is not the same for the new app, and when adding PartyKit to an existing app)
- updates the content around deployment
- rearranges the "Get Started" section so folks can faster get going

splits Quickstart pages to two, reorders sidebar

---

apps/docs/src/content/docs/examples/app-examples/falling-sand-game-three-js.md
apps/docs/src/content/docs/examples/app-examples/youtube-watch-party.md

This PR fixed a few broken links.
- In the sand-game, without the https:// for sand.graphics, it became a relative link I guess linking to https://docs.partykit.io/examples/app-examples/falling-sand-game-three-js/sand.graphics. 
- The youtube watch party link 404ed, so updated it to link to the live demo of *Namib Desert, watering hole livestream* example demo.
Thank you.

Fix broken links 

---

.changeset/sharp-schools-relate.md
examples/class/src/server.ts
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

Makes it possible to route requests without type hackery, as in https://github.com/partykit/example-sharding/blob/main/src/router.ts#L22
```diff
return lobby.parties.main
.get(id)
-     .fetch(req as unknown as RequestInit);
+     .fetch(req);
```

Fix stub.fetch types to allow forwarding Request directly

---

.changeset/warm-tables-jump.md
packages/partykit/src/config.ts

I had an issue with my project name previously, I had an underscore in the name of the project, and since the project name is included in the url for the party, I had two separate issues:
1. i could not deploy initially, there was a problem with uploading my files that was caused by the path name
2. i had a ERR_SSL_VERSION_OR_CIPHER_MISMATCH error in the client when trying to connect via partysocket
this second error I think was caused by subdomain issue in cloudflare https://developers.cloudflare.com/ssl/troubleshooting/version-cipher-mismatch/
this pr just adds a simple check to the config file to make sure that the name of the project will work as a url path segment

validating project name in config

---

.changeset/friendly-otters-fix.md
packages/partysocket/src/react.ts
packages/partysocket/src/use-handlers.ts
packages/partysocket/src/use-socket.ts
packages/partysocket/src/use-ws.ts

This PR fixes multiple issues in `usePartySocket` and `useWebSocket`:
- When props such as url, host, party etc were set dynamically, the socket would not reconnect and would remain connected with the existing parameters
- When event handlers were provided as functions, the socket would reconnect when function references changed
This change (seemingly) introduces some additional complexity to the code. In order to avoid duplication of said complexity between `usePartySocket` and `useWebSocket` I introduced some additional indirection, but I think that's worth it in this case.
Ideally we should have automated tests for this, but testing react hook lifecycles is a little tricky and we don't have infra set up for it, so in lieu I extensively tested this manually in different scenarios …

Improvements to usePartySocket (and useWebSocket) reliability

---

.changeset/selfish-kids-guess.md
packages/partysocket/src/index.ts

this adds another very simple check that the room name in the partysocket config is a valid path segment, there might be more options for room names depending on how you guys are implementing things on the back end, but at least now there is a central place to do the validation. Hoping this (at least partially) covers what is meant in issues #298  and #117 
this doesn't address connecting to parties from within a party server, but if pr #395 gets implemented, that issue will be solved
this was a little bit of guess work as to what the goals were here but I hope it helps!

adding room validation to partysocket

---

.changeset/thirty-taxis-provide.md
examples/test-node/package.json
examples/test-node/partykit.json
examples/test-node/script.mjs
examples/test-node/src/client.ts
examples/test-node/src/server.ts
examples/test-node/src/xyz.ts
examples/test-node/tsconfig.json
package-lock.json
packages/partysocket/src/ws.ts

When cloning websocket events in node, it looks like it misses the `data` field for messages. This patch adds it on to the cloned event.

partysocket: fix node usage

---

apps/site/party/presence.ts
apps/site/src/interactive/RoomContainer.jsx
apps/site/src/interactive/presence/presence-context.tsx
apps/site/src/interactive/presence/presence-schema.ts

- Removes Zod checks
- Removes partial presence updates from the client
- Doesn't send out empty presences in the sync message
- Changes the default room name
To do: fix assumptions around the "join" message

Gets homepage cursors working

---

apps/site/party/presence.ts
apps/site/src/components/content/Hero.astro
apps/site/src/components/content/Terminal.astro
apps/site/src/components/sections/Company.astro
apps/site/src/components/sections/Introduction.astro
apps/site/src/components/sections/Product.astro
apps/site/src/interactive/Voronoi.tsx
apps/site/src/interactive/presence/other-cursors.tsx
apps/site/src/layouts/Document.astro

- Fixes some Astro linting
- Updates the display count on the homepage to count only the connections with visible cursors (i.e. doesn't count smartphone users who are not touching)
- Puts the cursors on top the sticky header, otherwise they hide and make the display count look inaccurate

Linting and display nits

---

apps/site/src/components/Footer.astro

for some reason the bold was a bigger size than the not-bold in the h2

fix footer h2 issue on mobile

---

.changeset/unlucky-bottles-exercise.md
packages/partykit/schema.json
packages/partykit/src/cli.tsx
packages/partykit/src/config-schema.ts
packages/partykit/src/dev.tsx

This lets you specify aliases for modules, just like esbuild's aliases.

feat: config.build.alias  / config.serve.build.alias

---

.changeset/empty-dogs-share.md
packages/partykit/facade/source.ts
packages/partykit/src/dev.tsx

env vars have a 5kb limit, and people are hitting it. This should ease that off, without changing how we persist it ourselves.

Inject every var as it's own var instead of a big PARTYKIT_VARS object

---

.changeset/small-ladybugs-drive.md
.github/version-script.js
.github/workflows/prerelease.yml
.gitignore
examples/nitro/client/index.ts
examples/nitro/nitro.config.ts
examples/nitro/package.json
examples/nitro/party/test.ts
examples/nitro/partykit.json
examples/nitro/public/index.html
examples/nitro/routes/index.ts
examples/nitro/tsconfig.json
package-lock.json
packages/nitroparty/README.md
packages/nitroparty/entry.ts
packages/nitroparty/nitro.config.ts
packages/nitroparty/package.json
packages/nitroparty/tsconfig.json

This adds a nitro preset so folks can deploy nuxt/solidstart/etc apps directly to partykit. This is still a wip. Notes:
- server endpoints work, but getting the static asset handling to work in a bit of a pain. I think I need to change the "when" of waiting for the assets folder to appear before watching it
- it's not clear how to reference an npm package from nitro.config.ts (alternately, maybe I should submit it directly to the nitro repo)
- still needs process.env defines, or it crashes
- needs extensive testing, we'll get there

wip: first cut at getting nitro working with partykit

---

.changeset/lovely-goats-divide.md
packages/y-partykit/src/chunking.ts
packages/y-partykit/src/index.ts
packages/y-partykit/src/provider.ts

The class definition was eagerly looking for a WebSocket class, breaking in non-standards based environments (like node.js), leading to issues like https://github.com/partykit/partykit/issues/698. This removes the class definition, and uses the chunking function directly when required. I think this should fix the problem.

y-partykit remove ChunkedWebSocket class

---

.changeset/lemon-elephants-fry.md
packages/partysocket/package.json

As of now, discoverability of the `partysocket` package on NPM is really poor as it won't show-up when searching for `websocket` and its description is not meaningful outside of PartyKit.
I tried to fix that by 
- filling `description` with the tagline from `README.md`
- filling `keywords` with those used by [reconnecting-websocket](https://github.com/pladaria/reconnecting-websocket)
In the same way, once the package is installed (or found on npmjs.com) nothing links to this repository or PartyKit's homepage.
Fixing that by adding
- `homepage` pointing to the docs on PartyKit's homepage
- `bugs` pointing on this repo's issues page
- `repository` pointing to `partysocket` directory on this repo

chore: add metadata to `partysocket` for discoverability

---

.changeset/six-deers-hunt.md
examples/basic/src/server.ts
packages/partykit/inject-process.js
packages/partykit/src/config.ts
packages/partykit/src/tests/config.test.ts

(as well as `.env.local` during `dev`)

populate `process.env` with `.env` contents

---

.changeset/moody-cherries-drive.md
packages/partykit/src/dev.tsx

In some conditions, the custom build may be generating static assets, which will trigger the file watcher and infinitely loop. Moving it to the top before any effects are run fixes this.

dev: when we have a custom build, run it before starting any effects

---

.changeset/few-doors-move.md
packages/partykit/src/bin.tsx
packages/partykit/src/dev.tsx

when miniflare starts, it makes a request to get data to populate request.cf. This might not be desirable in some secure environments. This PR adds a flag to disable that behaviour.

dev: add a flag `--disable-request-cf-fetch`

---

.changeset/gentle-pigs-whisper.md
packages/y-partykit/src/provider.ts

y-partykit was failing in my environment (VSCode extension running in development mode) because 'crypto' is not defined. Simply adding an extra check to the already existing logic in order to fall back to insecure ID generation when 'crypto' is not defined.

y-partykit provider can generate IDs even if 'crypto' is not defined

---

apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/7-deploy-your-app.md

I noticed this when trying to deploy PartyKit from my CLI, here's what happens when I run `npm partykit deploy`:
```bash
$ npm partykit deploy
Unknown command: "partykit"
To see a list of supported npm commands, run:
npm help
```
Whereas when I look at the [Deploying your PartyKit Server](https://docs.partykit.io/guides/deploying-your-partykit-server/) page, it used `npx partykit deploy` which worked as expected.

docs: fix deploy partykit command

---

.changeset/new-cycles-tease.md
apps/site/public/schema.json
packages/partykit/facade/source.ts
packages/partykit/schema.json
packages/partykit/src/cli.tsx
packages/partykit/src/config-schema.ts
packages/partykit/src/dev.tsx
packages/partykit/src/server.ts

Instead of having to provision resources directly from the config, we'd like to bind to existing resources in users' CF accounts. For example, you have an R2 bucket that you'd like to access from your partykit project. Now, you can add this to your `partykit.json`:
```jsonc
{
//...
"bindings": {
"r2": {
"myBucket": "my-bucket-name"
}
}
}
```
Inside your project, you can now access the r2 bucket with `room.context.bindings.r2.myBucket` (or `lobby.bindings.r2.myBucket`).
We'll add more types of bindings in the near future.

feat: custom bindings for cloud-prem (part 1)

---

.changeset/purple-moles-appear.md
packages/partykit/facade/source.ts

The underlying PartyKit framework logs an error which gets forwarded to the same tail logger that is set up for the top level application. Since our team uses the tail logger to set up alarms, this specific `console.error` does get called every so often when we deploy. The error we receive is:
```
fetch error
Error: Durable Object reset because its code was updated.
```
The change here is to log a warn instead since this might still be worthwhile to log but the application itself can appropriately handle the actual error and decide how to move forward.

Update fetch error logging from console.error to console.warn

---

apps/site/package.json
package-lock.json
package.json
packages/create-partykit/package.json
packages/partykit/package.json

Saw an opportunity to recommend using [tsx](https://tsx.is) in a cool project.
If you prefer the `node` command, you can also do `node -r tsx/cjs`.
(Sorry for the unsolicited PR—feel free to close as well.)

chore: use tsx

---

apps/docs/src/content/docs/reference/partykit-ai.md

just fixing a typo I spotted on documentation:
`... PartyKit brings you models for a veriety of use cases, including: ...`
I'm changing veriety to variety.

fix: typo on variety

---

.changeset/slow-icons-jump.md
packages/partysocket/src/index.ts
packages/y-partykit/src/provider.ts

We currently assume that parties are routed to by /parties/:party/:room (or /party/:room for the default party.) However, there will be upcoming changes where parties can be routed to on the basis of any url (or even any other param, like a session id or whatever). This change lets clients connect with a `prefix` param. It also uses /parties/main/:room when connecting to the default party. This is not a breaking change, all projects should still just work as expected.

'prefix' option for PartySocket/YPartyKitProvider

---

.changeset/late-pumas-pull.md
package-lock.json
packages/y-partykit/package.json

Marks yjs and react as peerDependencies.
The react hook (and dependency) would ideally be in a separate package, but I've made it optional here.

Move y-partykit deps to peerDependencies

---

apps/docs/src/content/docs/reference/partyserver-api.md

Hey there! 👋🏻 I was pretty sure `onStart` runs when waking up from hibernation (and according [to this](https://github.com/threepointone/partyserver/blob/main/packages/partyserver/README.md#lifecycle-hooks) it does) so figured I should open a PR to update the docs here as well!

Include hibernation info

---

.changeset/spotty-pets-perform.md
packages/partysocket/src/index.ts
packages/partysocket/src/react.ts

renamed the previous prefix option to basePath, and added a new prefix option.
This is a breaking change, but since this was an undocumented feature, it's unlikely to affect anyone.

partysocket: add basePath, prefix

---

.changeset/path-prefix-thing.md
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx

Following the quickstart guide, on windows, with bun, when starting the dev server, I encountered this error:
```
🎈 PartyKit v0.0.100
---------------------
TypeError: Invalid URL
at new URL (node:internal/url:818:25)
at fileURLToPath (node:internal/url:1505:12)
at runBuild (file:///C:/Projects/Game/partykit/node_modules/partykit/dist/bin.mjs:89389:9)
at file:///C:/Projects/Game/partykit/node_modules/partykit/dist/bin.mjs:89683:5
at Og (file:///C:/Projects/Game/partykit/node_modules/partykit/dist/bin.mjs:10275:27)
at Ph (file:///C:/Projects/Game/partykit/node_modules/partykit/dist/bin.mjs:11708:31)
at Mh (file:///C:/Projects/Game/partykit/node_modules/partykit/dist/bin.mjs:11251:9)
at ad (file:///C:/Projects/Game/partykit/node_modules/partykit/dist/bin.mjs:7933:21)
at J …
```

Fix filePath broken on windows

---

apps/docs/src/content/docs/add-to-existing-project.md

This is an extremely minor PR. It simply corrects a misspelling in the [Add to Existing Project guide](https://docs.partykit.io/add-to-existing-project/).
Thanks!

Fix spelling error in existing project setup guide
