packages/partysocket/package.json
packages/y-partykit/package.json

This is kinda a follow-up to https://github.com/partykit/partykit/pull/133
cc @mellson @threepointone

Use `.mjs` for ESM files and add `types` condition to `exports`

---

examples/blocknote/package.json
examples/blocknote/partykit.json
examples/blocknote/public/index.html
examples/blocknote/src/client.tsx
examples/blocknote/src/randomUser.ts
examples/blocknote/src/server.ts
examples/blocknote/tsconfig.json
examples/blocknote/wrangler.toml
package-lock.json

This adds a demo for https://www.blocknotejs.org 🥳

blocknote demo

---

.changeset/hip-suns-greet.md
package-lock.json
packages/partykit/package.json
packages/partykit/scripts/build.ts
packages/partykit/src/async-cache.ts
packages/partykit/src/bin.tsx
packages/partykit/src/cli.ts
packages/partykit/src/commands/login.tsx
packages/partykit/src/commands/logout.tsx
packages/partykit/src/config.ts
packages/partykit/tsconfig.json
tsconfig.base.json

This uses [ink](https://github.com/vadimdemedes/ink) to render a couple of commands (login, logout). Introducing this in a small PR since it requires some changes to how we build stuff. Unfortunately this means we're not bundling packages into the package anymore, but we'll revisit that later. After this, we'll rewrite dev to use ink as well.

introduce ink

---

.changeset/green-cars-yell.md
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

importantly, this lets you call `ctx.waitUntil(promise)` in the `onBefore` fns.

add ctx to onBefore\* fns

---

.changeset/chilled-flies-shave.md
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

This exposes DO's `alarm` functionality. We already added the ability to set/remove alarms when we moved to workerd, this adds the api `onAlarm()`

feat: `onAlarm()`

---

.changeset/shiny-berries-deny.md
packages/partykit/src/dev.tsx

fixes https://github.com/partykit/partykit/issues/150

fix: dev on windows doesn't resolve correctly

---

.changeset/clean-ghosts-do.md
packages/partykit/facade/source.ts
packages/partykit/src/cli.ts

We'd previously landed multiparty support in https://github.com/partykit/partykit/pull/151, this enables us to publish as well.

feat: enable multiparty support when deploying

---

.github/workflows/pullrequest.yml
examples/monaco/package.json
package-lock.json
package.json
packages/partykit/package.json
packages/partykit/src/config.ts
packages/partysocket/package.json
packages/y-partykit/package.json

run checks on all OSes for PRs

---

packages/y-partykit/src/index.ts

This PR implements a read-only mode, where a user would not be allowed to make changes to a given room.

feat: add support for read-only connections

---

packages/partysocket/src/type-helper.ts
packages/partysocket/src/ws.ts

This is an alternative to #171

Refactor partysocket to use native EventTarget

---

.gitignore
packages/partysocket/LICENSE.txt
packages/partysocket/README.md
packages/partysocket/TODO.md
packages/partysocket/src/ws.ts

Cleaned up the text, corrected the examples, copied over the license, gave proper credit.

partysocket: a better README

---

.changeset/calm-taxis-scream.md
packages/partykit/facade/source.ts
packages/partykit/src/server.ts

(Extracted from https://github.com/partykit/partykit/pull/194 so we can land this separately)

Expose `parties` inside `onBeforeConnect` and `onBeforeRequest`.

---

.changeset/thick-books-jog.md
packages/y-partykit/src/provider.ts

expose connection id on YpartyKitProvider

---

examples/basic/src/client.ts
examples/basic/src/server.ts
examples/basic/src/xyz.ts
examples/basic/tsconfig.json
examples/blocknote/src/client.tsx
examples/blocknote/src/server.ts
examples/blocknote/tsconfig.json
examples/lexical/src/client.tsx
examples/lexical/src/server.ts
examples/lexical/tsconfig.json
examples/monaco/src/client.tsx
examples/monaco/src/server.ts
examples/monaco/tsconfig.json
examples/persistence/src/client.ts
examples/persistence/src/server.ts
examples/persistence/tsconfig.json
examples/wasm/package.json
examples/wasm/src/client.ts
examples/wasm/src/fib.asc.ts
examples/wasm/src/server.ts
examples/wasm/tsconfig.json
examples/yjs/src/client.ts
examples/yjs/src/server.ts
examples/yjs/tsconfig.json
package-lock.json
packages/partykit/src/tests/mock-console.ts

Now that @jevakallio fixed our types, the typescript configuration for example gets simplified drastically.

fix types under /examples

---

.changeset/great-plants-dance.md
package-lock.json
packages/partykit/package.json
packages/partykit/scripts/build.ts
packages/partykit/src/bin.tsx

This time it's integrated into the banner, so it's not as intrusive. It'll show up all the time in dev, but rarely in prod builds, so it's not annoying either.

add update-notifier again

---

.changeset/mighty-panthers-talk.md
packages/partykit/scripts/build.ts
packages/partykit/src/bin.tsx
packages/partykit/src/cli.tsx
packages/partykit/src/config.ts
packages/partykit/src/dev.tsx
packages/partykit/src/logger.tsx
packages/partykit/src/tests/deploy.test.ts
packages/partykit/src/tests/tail.test.ts

Copied some code from wrangler for better looking errors/warnings. This also enables sourcemaps only in dev.

feat: better errors/warnings

---

.changeset/six-rats-camp.md
packages/partykit/src/cli.tsx
packages/partykit/src/config.ts
packages/partykit/src/dev.tsx
packages/partykit/src/tests/deploy.test.ts
packages/partykit/src/tests/env.test.ts

This lets you pass a compatibility date and/or flags when uploading a worker. See https://developers.cloudflare.com/workers/configuration/compatibility-dates for more info.

feat: use compatibilityDate/compatibilityFlags if available

---

.changeset/shaggy-years-exercise.md
packages/partykit/src/bin.tsx
packages/partykit/src/cli.tsx
packages/partykit/src/config.ts
packages/partykit/src/dev.tsx
packages/partykit/src/tests/deploy.test.ts

- This adds a `--minify` / `config.minify` flag for both `dev` and `deploy` commands.
- This also adds a `partykit whoami` command

feat: add `--minify` and `whoami`

---

.changeset/orange-chefs-shave.md
packages/partykit/src/cli.tsx
packages/partykit/src/tests/deploy.test.ts
packages/partykit/src/tests/env.test.ts

This adds better messages for env commands. We were previously just spitting out some json, this cleans it up.

fix: better messages for env commands

---

.changeset/stupid-boxes-sparkle.md
packages/partykit/src/bin.tsx
packages/partykit/src/dev.tsx

add a `--verbose` flag for debugging dev

---

.changeset/brave-sloths-repeat.md
docs/serve.md
examples/basic/src/client.ts
examples/blocknote/src/client.tsx
examples/lexical/src/client.tsx
examples/monaco/src/client.tsx
examples/persistence/src/client.ts
examples/wasm/src/client.ts
examples/yjs/src/client.ts
packages/partykit/init-template/src/client.tsx
packages/partykit/init-template/src/server.ts
packages/partykit/init-template/tsconfig.json
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx
packages/partykit/src/tests/deploy.test.ts
packages/partysocket/src/index.ts
packages/y-partykit/src/provider.ts

- replace `process.env.PARTYKIT_HOST` with just `PARTYKIT_HOST`
- add a `tsconfig.json`
- add partykit to devDependencies in `init`
- strip protocol from host (partysocket, y-partykit)

small tweaks to `init`

---

.changeset/funny-clouds-lie.md
docs/serve.md
packages/partykit/schema.json
packages/partykit/src/cli.tsx
packages/partykit/src/config-schema.ts
packages/partykit/src/dev.tsx

Fixes https://github.com/partykit/partykit/issues/254

expose `external` for asset bundling config

---

.changeset/rude-jokes-brake.md
examples/wasm/package.json
examples/wasm/partykit.json
packages/partykit/src/cli.tsx
packages/partykit/src/dev.tsx
packages/partykit/src/tests/deploy.test.ts

Looks like importing wasm modules was broken, this should fix it

fix: wasm modules

---

.changeset/breezy-flies-rush.md
packages/partykit/src/cli.tsx

Few bugs I found while fixing #304

Fix edge case bugs in init

---

.changeset/three-cycles-run.md
examples/basic/src/xyz.ts
packages/partykit/facade/source.ts

sigh. we were always fetching from the main party. This fix routest he request to the correct sub party.

fix: route sub party requests correctly

---

.changeset/fresh-keys-cross.md
packages/partykit/src/dev.tsx

We weren't reading config correctly in dev, this fixes it

use the right config/options in dev

---

apps/docs/astro.config.mjs

this PR fix the social(github) link in the docs

fix(social): github social link

---

.changeset/lucky-spies-fry.md
.github/workflows/prerelease.yml
.github/workflows/pullrequest.yml
.github/workflows/release.yml
package-lock.json
packages/partykit/package.json

we shouldn't use bun install until https://github.com/partykit/partykit/pull/352 lands

use npm ci for CI installs

---

apps/docs/astro.config.mjs

this PR fixes the "edit this page" button.

fixes edit link

---

apps/blog/.astro/types.d.ts
apps/blog/src/config.ts
apps/blog/src/content/blog/customizing-astropaper-theme-color-schemes.md
apps/blog/src/content/blog/how-to-configure-astropaper-theme.md
apps/blog/src/pages/index.astro

We currently only show 4 (because that's the default setting.) Let's show more!

blog: Show 10 posts per page

---

.changeset/short-grapes-mix.md
packages/partykit/src/bin.tsx
packages/partykit/src/cli.tsx

Fixes https://github.com/partykit/partykit/issues/425

Add --force/-f flag to `partykit delete`

---

apps/docs/src/content/docs/guides/persisting-state-into-storage.md

I think this might be a typo, it tripped me up when I started persisting data :)

Update example for getting all the rooms messages onStart

---

apps/blog/src/content/blog/live-polls-with-stencil.md

Fixes typo in social card image URL

---

apps/docs/src/content/docs/guides/index.md

`sender` does not exist in `onConnect`. i assume `connection` is the correct one.

fix typo in guide

---

.changeset/polite-ducks-hide.md
apps/docs/src/content/docs/reference/partyserver-api.md

Landing this when we land the new API to stable release.

Update documentation for Connection.state

---

.changeset/smart-poets-punch.md
packages/partykit/src/server.ts

Currently types don't allow you to clear state

Make connection.setState accept null

---

apps/docs/src/content/docs/examples/index.mdx

links up the blog post to the examples page

adds link to the examples

---

.changeset/eight-hornets-impress.md
packages/partysocket/src/react.ts

Because default exports are the worst

feat: add named usePartySocket export

---

.changeset/clever-nails-bathe.md
package-lock.json
packages/partykit/package.json
packages/partykit/src/cli.tsx
packages/partykit/src/server.ts
packages/partykit/src/tests/deploy.test.ts

Runs asset uploads in parallel. Adds a pre-upload step to validate assets before attempting to upload, so user doesn't have to wait until end of the upload batch before finding there was an error.

Parallellize asset uploads + fail fast

---

apps/docs/.astro/types.d.ts
apps/docs/astro.config.mjs
apps/docs/src/content/docs/add-to-existing-project.md
apps/docs/src/content/docs/examples/app-examples/falling-sand-game-three-js.md
apps/docs/src/content/docs/examples/app-examples/live-polls-app.md
apps/docs/src/content/docs/guides/deploying-your-partykit-server.md
apps/docs/src/content/docs/guides/managing-environment-variables.md
apps/docs/src/content/docs/quickstart.md
apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/2-set-up-server.md
apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/3-hook-up-data-to-the-server.md
apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/4-add-websockets.md
apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/5-broadcast-the-change.md
apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/6-add-storage.md
apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/7-deploy-your-app.md
apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/index.md

This PR:
- reviews the tutorial from yesterday
- adds the poll app example

Tutorial review + new example

---

apps/docs/src/content/docs/guides/deploying-your-partykit-server.md

just changing the link on the deployment guide page to be correct, right now it gives a 404

just changing a link to be correct

---

apps/docs/src/content/docs/add-to-existing-project.md
apps/docs/src/content/docs/guides/authentication.md
apps/docs/src/content/docs/guides/handling-binary-messages.md
apps/docs/src/content/docs/guides/index.md
apps/docs/src/content/docs/guides/managing-environment-variables.md
apps/docs/src/content/docs/guides/rate-limiting-messages.md
apps/docs/src/content/docs/guides/responding-to-http-requests.md
apps/docs/src/content/docs/guides/scheduling-tasks-with-alarms.md
apps/docs/src/content/docs/guides/setting-up-ci-cd-with-github-actions.md
apps/docs/src/content/docs/guides/using-multiple-parties-per-project.md
apps/docs/src/content/docs/guides/validating-client-inputs.md

Adds more guides to the docs:
- Alarms
- Rate limiting
- Validating client inputs with Zod
- Binary message formats, and encoding with MessagePack

Add more guides

---

apps/docs/src/content/docs/index.mdx

'ą' character
Noticed while reading the documentation. So created a PR for the same to remove it

Fixed type error

---

apps/site-new/package.json
apps/site-new/scripts/fetch-blog-entries.js
apps/site-new/src/blog.json
package-lock.json

This fetches blog post entries from the blog's rss feed and writes it to disk as json, so we can consume it and render it on the homepage.

fetch blog entries

---

apps/docs/src/content/docs/tutorials/add-partykit-to-a-nextjs-app/3-hook-up-data-to-the-server.md

Noticed `messages.In` typo and added some commas.

[docs] Punctuation fixes for 3-hook-up-data-to-the-server.md

---

apps/site/party/presence.ts
apps/site/src/interactive/RoomContainer.jsx
apps/site/src/interactive/Voronoi.tsx
apps/site/src/interactive/presence/presence-context.tsx
apps/site/src/interactive/presence/presence-schema.ts

- Removes join message and passes initial presence in the query string
- Turns hibernate back on

Remove join message

---

apps/site/src/interactive/Voronoi.tsx

Fix for the case there is just one user on the site

Display fix

---

apps/docs/src/content/docs/reference/partysocket-api.md
packages/partysocket/README.md

docs(partysocket): new method updateProperties

---

.changeset/wet-meals-thank.md
packages/partykit/src/cli.tsx

- don't ask to install partykit if already in deps
- use typescript by default unless explicitly opted out

init tweaks

---

apps/docs/package.json
apps/docs/src/content/docs/glossary.md
package-lock.json

Update glossary to fix empty deep link from [docs page](https://docs.partykit.io/how-partykit-works/#web-server)

docs: Update glossary.md to include Durable object definition

---

apps/docs/.astro/types.d.ts
apps/docs/src/content/docs/guides/debugging.md

Extend the docs with `debugging` guide that points to the cloudflare article on how to debug cloudflare workers

debugging guide in the docs

---

.changeset/friendly-points-hug.md
packages/y-partykit/src/provider.ts

via https://github.com/partykit/partykit/issues/766

y-partykit: let user force protocol

---

.changeset/two-rockets-report.md
packages/partykit/src/bin.tsx
packages/partykit/src/dev.tsx

for folks who want to visit `https://localhost...` in dev

`dev --https --https-key-path <path> --https-cert-path <path>`

---

.changeset/big-spoons-smoke.md

PartySocket's been pretty stable, so it's time to cut a v1. We have plans for future features, but it's pretty good right now, so let's ship it.

PartySocket V1

---

.changeset/popular-cougars-love.md
package-lock.json
packages/partykit-ai/package.json
patches/@cloudflare+ai+1.0.53.patch

https://blog.cloudflare.com/february-28-2024-workersai-catalog-update

partykit-ai: new models!

---

examples/blocknote/package.json
examples/blocknote/src/client.tsx
package-lock.json

Hi, we recently updated BlockNote to v0.12.0 which introduced a number of small breaking changes. This PR updates the example to use the new version.

chore: Updated BlockNote example

---

apps/docs/src/content/docs/glossary.md

corrected the word "persistent"

fixed typo in glossary.md

---

examples/blocknote/package.json
examples/blocknote/src/client.tsx
package-lock.json

Hi, back with another version update for BlockNote, this time to 0.14.1:)

chore: BlockNote 0.14.1 update

---

apps/docs/src/content/docs/guides/deploy-to-cloudflare.md

From @threepointone in the Discord

Reflect that PartyKit Cloud-Prem is now free

---

.changeset/fast-buckets-jump.md
packages/partysocket/src/ws.ts

update websocket implementation to handle connection failures gracefully
